### ISSUE TITLE
Ignores "Do Not Lint Files Ignored By VCS" in linter

### ISSUE THREAD

**Issue by jda0** [AtomLinter/linter-flow#150]
It is not clear if this is a problem in `linter` or `linter-flow`

Reproduce:
- Tick "Do Not Lint Files Ignored By VCS" in `linter` package settings
- `npm install flow-remove-types flow-bin`
- `echo "" > .gitignore`
- `touch .flowconfig`
- `echo "// @flow" > index.js` [or create file on Windows]

Now open `index.js` and `Project` has 13 warnings from `\node_modules\flow-remove-types\test\source.js`

EDIT: this problem does not seem to occur if you `echo "/* @flow */"` instead of `// @flow`. This may be intentional? In that case a clearer error message may be preferable

**Comment by Arcanemagus** [comment]
The setting in Linter controls whether it will trigger a lint for a file based on the VCS setting.

I'm _guessing_ that what is going on here is that since you are opening `index.js` (which would be allowed), `flow` is running on that... but `flow` returns result for _all_ files in what _it_ considers to be the project, and from what you described you haven't told `flow` to ignore the file... so it gives `linter-flow` back results for the file.

I would lean towards this being a misconfiguration issue as far as how you have `flow` configured, but one could definitely argue that this is a bug in `Linter` that it is accepting / not discarding the messages for a VCS ignored file. @steelbrain is that something you want to take on in Linter or just leave it as is?

**Comment by steelbrain** [comment]
This is actually something that has to do with Flow. Linter cannot control VCS ignored status of Project-Scoped linters.

The errors you get from your deps are because:
1. Flow checks entire project
2. Your deps are faulty, they should not include `.flowconfig` in the npm dist; they do right now :)

You can "supress" this error in flow by ignoring the node_modules directory, but then everytime you require a node module you'll get a Flow warning. Therefore the best course of action is fixing the fautly dep or ignoring the errors

**Comment by Arcanemagus** [comment]
Closing this as there is nothing that can be done about it here, you should be ignoring those files in your Flow configuration.

Also, looking back over your steps you never actually create a git repository in this test, and you don't have `node_modules` ignored even if you did, so even if we did go crazy and implement checking the results against the VCS before sending them onto Linter that still would show in your example 😕.
