### ISSUE TITLE
`suppress_comment` comments are ignored

### ISSUE THREAD

**Issue by elliottsj** [AtomLinter/linter-flow#36]
If I define a [`suppress_comment`](http://flowtype.org/docs/advanced-configuration.html) regex like this:

```
suppress_comment= \\(.\\|\n\\)*\\$FlowIssue
```

`flow check` properly ignores the line following the comment, but linter-flow does not:

<img width="442" alt="screenshot 2015-11-08 17 40 26" src="https://cloud.githubusercontent.com/assets/2177366/11023186/d024f928-863f-11e5-8d3e-9090ad68be79.png">

**Comment by elliottsj** [comment]
Related: https://github.com/facebook/flow/issues/1008

**Comment by nmn** [comment]
This is probably a bug in flow itself, as obviously the linter gets its errors from flow. It could be a bug specific to `flow check-contents`.

I'll look into it and create an issue on flow if that is needed.

**Comment by nmn** [comment]
It is possible for me to add a patch that would ignore errors in the linter. However, I think the correct solution would be for it to be fixed in flow itself.

@steelbrain @Adezandee What do you think. Do you want to add a patch to linter-flow that fixes this issue while we wait for flow to fix it on their end?

**Comment by Arcanemagus** [comment]
If the errors specific to `flow check-contents` are simple enough to detect you might write a patch with an issue filed to remind you to remove it when it is fixed in `flow`, in the linters I've worked on though for the most part we just leave it up to the provider.

**Comment by steelbrain** [comment]
@nmn If I recall correctly, flow doesn't search for `.flowconfig` on `flow check-contents`, therefore it doesn't know if it's supposed to ignore those errors. We could ask flow peeps to check for `.flowconfig` and if it's available, use it.

As a workaround, people experiencing this issue can disable `lintOnFly`. or if we get a lot of requests for this, we could patch it in this package.

**Comment by nmn** [comment]
@steelbrain I don't think the issue is that flow doesn't look at the `.flowconfig` file. The `.flowconfig` file is used when starting the flow server, and `check-contents` only runs after the server is already running.

Also, it correctly reads the other config in the file such as [lib] and support for getter & settters and decorators.

I think it's just a random flow bug. That said, there are a large number of outstanding issues on flow, so it may or may not get fixed in the near future.

On the other hand, handling it in the linter will be pretty trivial.

**Comment by steelbrain** [comment]
@nmn If you think it's trivial to handle this in this linter, go for it!

**Comment by elliottsj** [comment]
`suppress_comment` appears to work for me now using recent flow versions. Currently using v0.22.1.
