### ISSUE TITLE
Notifications [Close All] button doesn't work

### ISSUE THREAD

**Issue by AgentME** [AtomLinter/linter-flow#46]
Every time when I start up Atom on a project with Flow, these notifications appear for a few seconds and block access to some of my tabs. There's a [Close All] button on them which seems like it would be handy, but it doesn't work. (Are these notifications maybe provided by linter or Atom itself? Maybe the issue should be for one of them.)

![screen shot 2015-12-11 at 2 40 21 pm](https://cloud.githubusercontent.com/assets/577345/11823527/469f26c2-a329-11e5-9cd2-b64e8ba8e86d.png)

**Comment by Arcanemagus** [comment]
Those notifications are handled by Atom, and the Close All button should definitely work. If it isn't working you should file an issue over on the Atom issue tracker.

Marking as closed since this isn't an issue with linter-flow, although please reference any issue file here so we can follow the progress :wink:.
